import os
import time

f = open("/var/lib/dhcp/dhcpd.leases")
d = f.read()
f.close()

records = {}
leases = d.split("\nlease ")
leases.pop(0)
for x in leases:
	l = x.split("\n")
	ip = l[0].replace("{","").replace(" ","")
	hostname =''
	ethernet=''
	for a in l:
		if 'client-hostname ' in a:
			hostname = a.replace("client-hostname ","").replace(" ","").replace(";","").replace('"','')

		if 'hardware ethernet ' in a:
			ethernet = a.replace("hardware ethernet ","").replace(" ","").replace(";","")

	records[ip] = {'ip':ip,'hostname':hostname,'ethernet':ethernet}

f = open("/etc/hosts",'r')
d = f.read()
f.close()

if "#### GENERATED BY updateHosts ####" not in d:
	d += "\n#### GENERATED BY updateHosts ####\n"

h = d.split("#### GENERATED BY updateHosts ####")
n = h[0]
n += "#### GENERATED BY updateHosts ####"
n += "\n"
n += "# Last updated: " + time.ctime()
n += "\n"
for i in records:
	x = records[i]
	if x['ip'] != '' and x['hostname'] != '':
		n += x['ip'] + "\t" + x['hostname'] + "\n"

print n

f = open("/etc/hosts",'w')
f.write(n)
f.close()
os.system("/etc/init.d/dnsmasq restart")
